# Generated by Django 3.1.6 on 2021-02-17 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default=None, max_length=100)),
                ('Icon', models.FileField(upload_to='media/Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuilderName', models.CharField(default=None, max_length=50)),
                ('Logo', models.FileField(upload_to='media/BuilderLogo')),
                ('SolePartner', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserContactData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default=None, max_length=12)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyList',
            fields=[
                ('Prop_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PropertyName', models.CharField(max_length=60)),
                ('Property_Image', models.ImageField(upload_to='media/Property_images')),
                ('Property_Price', models.CharField(max_length=20)),
                ('Property_Description', models.TextField(max_length=500)),
                ('PropertyStatus', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Ready to move', 'Ready to move')], max_length=20)),
                ('Property_Type', models.CharField(choices=[('Residential', 'Residentail'), ('Commercial', 'Commercial')], default='Residential', max_length=20)),
                ('BuilderName', models.CharField(max_length=30)),
                ('Location', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Punjab', 'Punjab')], max_length=20)),
                ('PropertyAddress', models.CharField(max_length=100)),
                ('Area_in_sqft', models.CharField(max_length=20)),
                ('BHK', models.CharField(max_length=20)),
                ('Avaliable_For', models.CharField(default='Sale', max_length=20)),
                ('Project_Area', models.CharField(default=None, max_length=100)),
                ('PerSqftPrice', models.CharField(default=None, max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('Property_Amenities', models.ManyToManyField(to='SHIApp.Amenities')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='media/IndividualPropImgs')),
                ('Image_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHIApp.propertylist')),
            ],
        ),
    ]
