# Generated by Django 3.1.6 on 2021-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0003_auto_20210217_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='Icon',
            field=models.FileField(upload_to='static/Icon'),
        ),
        migrations.AlterField(
            model_name='builder',
            name='Logo',
            field=models.FileField(upload_to='static/BuilderLogo'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='Images',
            field=models.ImageField(upload_to='static/IndividualPropImgs'),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='Property_Image',
            field=models.ImageField(upload_to='static/Property_images'),
        ),
    ]
