# Generated by Django 3.1.6 on 2021-02-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0004_auto_20210217_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': 'Amenities'},
        ),
    ]
