# Generated by Django 3.1.6 on 2021-02-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0006_auto_20210218_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylist',
            name='PropertyName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
