# Generated by Django 3.1.6 on 2021-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0007_auto_20210219_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylist',
            name='Google_Map',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
