# Generated by Django 3.1.6 on 2021-02-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0008_propertylist_google_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResumeData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default=None, max_length=12)),
                ('vacancy', models.CharField(default='', max_length=100)),
                ('message', models.TextField(default='')),
            ],
        ),
    ]
