# Generated by Django 3.1.6 on 2021-02-21 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0009_userresumedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyContact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default=None, max_length=12)),
                ('property_Name', models.CharField(default='', max_length=100)),
                ('message', models.TextField(default='')),
                ('contactTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='usercontactdata',
            name='contact_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userresumedata',
            name='resume_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
