# Generated by Django 3.1.6 on 2021-02-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0010_auto_20210221_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresumedata',
            old_name='resume_time',
            new_name='resumetime',
        ),
    ]
