# Generated by Django 3.1.6 on 2021-03-11 09:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0014_propertylist_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotPropertyList',
            fields=[
                ('Prop_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PropertyName', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(default='', max_length=550, null=True)),
                ('SearchName', models.CharField(default='', max_length=100)),
                ('Property_Image', models.ImageField(upload_to='static/HotProperty_images')),
                ('Master_Plan', models.ImageField(blank=True, default='', upload_to='static/HotMaster_Plans')),
                ('Video', models.FileField(blank=True, default='', upload_to='static/HotPropVideos')),
                ('Property_Price', models.CharField(max_length=50)),
                ('Property_Description', models.TextField(max_length=1000)),
                ('PropertyStatus', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Ready to move', 'Ready to move')], max_length=50)),
                ('Property_Type', models.CharField(choices=[('Residential', 'Residentail'), ('Commercial', 'Commercial')], default='Residential', max_length=20)),
                ('SubPropType', models.CharField(choices=[('Plot', 'Plot'), ('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Rowhouse', 'Rowhouse'), ('Farmhouse', 'Farmhouse')], default='', max_length=60)),
                ('Location', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Punjab', 'Punjab')], max_length=50)),
                ('PropertyAddress', models.CharField(max_length=100)),
                ('BHK', models.CharField(max_length=50)),
                ('Avaliable_For', models.CharField(default='Sale', max_length=50)),
                ('Project_Area', models.CharField(default=None, max_length=100)),
                ('PerSqftPrice', models.CharField(default=None, max_length=100)),
                ('Google_Map', models.CharField(default='', max_length=10000)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('BuilderName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SHIApp.builder')),
                ('Property_Amenities', models.ManyToManyField(to='SHIApp.Amenities')),
            ],
        ),
        migrations.CreateModel(
            name='HotPropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='static/HotIndividualPropImgs')),
                ('Image_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SHIApp.hotpropertylist')),
            ],
        ),
    ]
