# Generated by Django 3.1.6 on 2021-03-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHIApp', '0015_hotpropertyimages_hotpropertylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpropertylist',
            name='Floor_Plan_1BHK',
            field=models.ImageField(blank=True, default='', upload_to='static/Hot_Prop_Floor_Plan_1BHK'),
        ),
        migrations.AddField(
            model_name='hotpropertylist',
            name='Floor_Plan_2BHK',
            field=models.ImageField(blank=True, default='', upload_to='static/Hot_Prop_Floor_Plan_2BHK'),
        ),
        migrations.AddField(
            model_name='hotpropertylist',
            name='Floor_Plan_3BHK',
            field=models.ImageField(blank=True, default='', upload_to='static/Hot_Prop_Floor_Plan_3BHK'),
        ),
        migrations.AddField(
            model_name='hotpropertylist',
            name='Floor_Plan_4BHK',
            field=models.ImageField(blank=True, default='', upload_to='static/Hot_Prop_Floor_Plan_4BHK'),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='Floor_Plan_1BHK',
            field=models.ImageField(blank=True, default='', upload_to='static/Floor_Plan_1BHK'),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='Floor_Plan_2BHK',
            field=models.ImageField(blank=True, default='', upload_to='static/Floor_Plan_2BHK'),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='Floor_Plan_3BHK',
            field=models.ImageField(blank=True, default='', upload_to='static/Floor_Plan_3BHK'),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='Floor_Plan_4BHK',
            field=models.ImageField(blank=True, default='', upload_to='static/Floor_Plan_4BHK'),
        ),
    ]
